FROM docker.io/dmto0l2022/python_base_api_1:latest
WORKDIR /workdir/

RUN /workdir/app/env/bin/pip3 freeze
COPY . /workdir/.
##RUN ls -R /workdir/
CMD ["gunicorn"  , "--bind", "0.0.0.0:8004", "wsgi:application"]
