FROM localhost/my-pythonbaseapi-1:latest
COPY requirements.txt /workdir/requirements.txt
RUN /workdir/app/env/bin/pip3 install -r /workdir/requirements.txt
RUN /workdir/app/env/bin/pip3 freeze
COPY . /workdir/.
##RUN ls -R /workdir/
CMD ["/workdir/app/env/bin/gunicorn"  , "--bind", "0.0.0.0:8004", "workdir.wsgi:application"]
