FROM localhost/python_base_frontend_1:latest
WORKDIR /workdir/

RUN /workdir/app/env/bin/pip3 freeze
COPY . /workdir/.
##RUN ls -R /workdir/
CMD ["gunicorn"  , "--bind", "0.0.0.0:8002", "wsgi:application"]
