FROM docker.io/dmto0l2022/python_base_frontend_1:latest
WORKDIR /workdir/
COPY requirements.txt /workdir/requirements.txt
RUN /workdir/app/env/bin/pip3 install -r /workdir/requirements.txt

RUN /workdir/app/env/bin/pip3 freeze
COPY . /workdir/.
##RUN ls -R /workdir/
CMD ["gunicorn"  , "--bind", "0.0.0.0:8002", "wsgi:application"]
