# Generated by Django 4.0.5 on 2022-07-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0003_exampleplotdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamplePlotData',
        ),
    ]
